<a href="https://colab.research.google.com/github/amknm2026/BAN2026/blob/main/BAN-130/GA1/GA_Part12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<H1><b>BAN130 - Group Assignment
Python Implementation for Data Analysis </b></H1>

Group 1 [Please add your names ordered by last name]
  Adriana Moura

Part 1: Exploring and Filtering Data (10%)
1. Load the EU_OCC.sas7bdat file and examine the column names and values.
2. Filter the dataset to include only rows where YearMon starts with "2016".
3. Format the columns Hotel, ShortStay, and Camp to include commas as thousand
separators.
4. Drop the column Geo from the dataset.
Deliverables: Python script that completes the above tasks, with clear comments

In [206]:
# 1.Load the EU_OCC.sas7bdat file and examine the column names and values.
import pandas as pd
df_EU_OCC = pd.read_sas('https://raw.githubusercontent.com/amknm2026/BAN2026/main/BAN-130/GA1/Data/eu_occ.sas7bdat', format='sas7bdat',encoding="cp1252")

print ('1. Load EU_OCC.sas7bdat file')
print ('Display Sample for sanity check');
display (df_EU_OCC.head(5))
print ()

# format column name and data type information for easier view
dtypes_table = (
  df_EU_OCC.dtypes
  .reset_index()
  .rename(columns={"index":"Column Name",0:"Data Type"})
  )
print ('Column Names and data Type information \n')
display (dtypes_table)


# there are no numbers, so no need to describe the dataset
print ('\n All variables are character, there are no summary info (mean, mediam) \n')

# format column name and number of empty occurrencies for easier view
dvempty_table = (
    df_EU_OCC.isna().sum()
    .reset_index()
    .rename(columns={"index":"Column Name",0:"Empty Values"})
)

print ('\n Total Missing Values \n')
display (dvempty_table);
print ()

#identify missing values for Hotel and select 5 records (sample)
df_HotelNA = df_EU_OCC[df_EU_OCC.Hotel.isna()].sample(5)

#identify missing values for ShotStay
df_SSNA = df_EU_OCC[df_EU_OCC.ShortStay.isna()]
#remove any matches with df_HotelNA and select 5 records (sample)
df_SSNA = pd.concat([df_SSNA,df_HotelNA]).drop_duplicates(keep=False).sample(5)

#identify missing values for Camp
df_CampNA = df_EU_OCC[df_EU_OCC.Camp.isna()]
#remove any matches with df_HotelNA and ShortStay
df_CampNA = pd.concat([df_CampNA,df_HotelNA, df_SSNA]).drop_duplicates(keep=False).sample(5)

len(df_CampNA)
print ('\n Missing values - Hotel -Sample \n ')
display(df_HotelNA)

print ('\n Missing values - ShortStay -Sample \n')
display(df_SSNA)

print ('\n Missing values - Camp - Sample \n')
display(df_CampNA)

1. Load EU_OCC.sas7bdat file
Display Sample for sanity check

  Geo  Country  YearMon       Hotel  ShortStay       Camp
0  AT  Austria  2017M09   7768564.0  1453530.0   524121.0
1  AT  Austria  2017M08  11353432.0  3140217.0  1997801.0
2  AT  Austria  2017M07  10124106.0  2836425.0  1752605.0
3  AT  Austria  2017M06   7391827.0  1568683.0   914560.0
4  AT  Austria  2017M05   5068884.0  1054870.0   359560.0

Column Names and data Type information

  Column Name Data Type
0         Geo    object
1     Country    object
2     YearMon    object
3       Hotel   float64
4   ShortStay   float64
5        Camp   float64

All variables are character, there are no summary info (mean, mediam)

Total Missing Values

  Column Name  Empty Values
0         Geo             0
1     Country             0
2     YearMon             0
3       Hotel           101
4   ShortStay          2801
5        Camp          2803

Missing values - Sample Hotel

,Geo,Country,YearMon,Hotel,ShortStay,Camp
4692,UK,United Kingdom,2011M09,NaN,NaN,NaN
3023,MK,Former Yugoslav Republic of Macedonia,2013M04,NaN,NaN,NaN
3099,MK,Former Yugoslav Republic of Macedonia,2006M12,NaN,NaN,NaN
3019,MK,Former Yugoslav Republic of Macedonia,2013M08,NaN,NaN,NaN
3016,MK,Former Yugoslav Republic of Macedonia,2013M11,NaN,NaN,NaN

     Geo   Country  YearMon       Hotel  ShortStay  Camp
4613  SK  Slovakia  2004M07    736588.0        NaN   NaN
947   DE   Germany  2007M07  21580370.0        NaN   NaN
924   DE   Germany  2009M06  20005925.0        NaN   NaN
419   BG  Bulgaria  2010M04    503728.0        NaN   NaN
1801  FR    France  2005M02  12480740.0        NaN   NaN

,Geo,Country,YearMon,Hotel,ShortStay,Camp
3760,PL,Poland,2006M11,1646960.0,NaN,NaN
3757,PL,Poland,2007M02,1534703.0,NaN,NaN
2559,LT,Lithuania,2010M09,230356.0,NaN,NaN
4409,SI,Slovenia,2007M10,456477.0,NaN,NaN
3072,MK,Former Yugoslav Republic of Macedonia,2009M03,44885.0,NaN,NaN

In [124]:
# 2.Filter the dataset to include only rows where YearMon starts with "2016".
df_EU_OCC_2016 = df_EU_OCC[df_EU_OCC.YearMon.str.startswith('2016')]

print ('2. Filter the dataset to include only rows where YearMon starts with "2016"')
print(f'Number of records: ',len(df_EU_OCC_2016) )
print('Sample - 5 records \n')
display(df_EU_OCC_2016.sample(5));

2. Filter the dataset to include only rows where YearMon starts with "2016"
Number of records:  348
Sample - 5 records

     Geo  Country  YearMon      Hotel  ShortStay       Camp
1499  FI  Finland  2016M07  2070553.0   283067.0   651006.0
1994  HU  Hungary  2016M07  2888772.0  1184900.0   629980.0
18    AT  Austria  2016M03  9595174.0  2726831.0   144641.0
4140  SE   Sweden  2016M06  3197630.0   548307.0  2163853.0
2157  IS  Iceland  2016M09   486576.0   182341.0    48337.0

In [119]:
# 3.Format the columns Hotel, ShortStay, and Camp to include commas as thousand separators.
# defined a named function rather than using a lambda (since we are beginners)
def add_thousand_separator(value):
  if pd.notna(value):
    formatted_value = '{:,}'.format(value)
    return formatted_value
  else:
    return value

#   Data conversion has not been requested, only keep character variables
#   To prevent conversion issues (if required converting to numeric) , a new dataset will be created to store these numbers
df_formatted_values = df_EU_OCC_2016.copy();


# select the columns required
cols =  ["Hotel", "ShortStay", "Camp"]
# applies the change to the 3 columns
for column_name in cols:
  df_formatted_values[column_name]= df_formatted_values[column_name].map(add_thousand_separator)

print ('3. Records from 2016 - Hotel, Shortsay and Camp columns including thousands separators')
print (f'Total Records from 2016 (sanity check): {len(df_formatted_values)} \n')
display(df_formatted_values.sample(5))

print ()
# 4.Drop the column Geo from the dataset. Deliverables: Python script that completes the above tasks, with clear comments
# will continue with previous formatted dataset (dt_formatted_values )
df_formatted_values.drop(columns=['Geo'], inplace=True)
print ('4. Records from 2016 - Hotel, Shortsay and Camp columns including thousands separators, Geo column removed')
print (f'Total Records (sanity check): {len(df_formatted_values)} \n')
display(df_formatted_values.sample(5))

3. Records from 2016 - Hotel, Shortsay and Camp columns including thousands separators
Total Records from 2016 (sanity check): 348

     Geo         Country  YearMon         Hotel     ShortStay          Camp
4633  UK  United Kingdom  2016M08  20,998,957.0  10,918,043.0  10,935,663.0
1330  ES           Spain  2016M11  17,134,705.0   4,774,532.0     943,648.0
19    AT         Austria  2016M02  10,318,480.0   3,128,010.0     132,035.0
2156  IS         Iceland  2016M10     391,738.0     118,162.0           0.0
3316  NL     Netherlands  2016M05   4,217,752.0   4,233,956.0   2,821,168.0

4. Records from 2016 - Hotel, Shortsay and Camp columns including thousands separators, Geo column removed
Total Records (sanity check): 348

             Country  YearMon         Hotel     ShortStay          Camp
671   Czech Republic  2016M10   3,182,000.0     656,623.0      16,017.0
3145           Malta  2016M11     601,743.0      18,377.0           0.0
2324           Italy  2016M07  42,248,644.0  15,641,291.0  14,194,478.0
4308        Slovenia  2016M03     479,117.0     120,750.0      26,633.0
1009         Denmark  2016M02     861,242.0     346,233.0      98,870.0

Part 2: Creating and Formatting Columns (15%)
1. Load the np_summary.sas7bdat file.
2. Create a new column SqMiles by converting Acres to square miles (Acres * 0.0015625).
3. Create a new column Camping as the sum of OtherCamping, TentCampers, RVCampers,
and BackcountryCampers.
4. Format SqMiles and Camping columns to include commas and zero decimal places.
5. Save the updated dataset with only the following columns: Reg, ParkName, DayVisits,
OtherLodging, Acres, SqMiles, Camping.
Deliverables: Python script with the processed DataFrame.

In [228]:
#1. Load the np_summary.sas7bdat file.

import pandas as pd
df_np_summary = pd.read_sas('https://raw.githubusercontent.com/amknm2026/BAN2026/main/BAN-130/GA1/Data/np_summary.sas7bdat', format='sas7bdat',encoding="cp1252")

print ('Load np_summary data file')
print (f'Number of Rows: {df_np_summary.shape[0]} ')
print (f'Number of Columns: {df_np_summary.shape[1]}\n' )


print ('Sample for sanity checking\n')
display(df_np_summary.sample(5))


#verify column information
# format column name and data type information for easier view
df_np_summary_types = (
  df_np_summary.dtypes
  .reset_index()
  .rename(columns={"index":"Column Name",0:"Data Type"})
  )

print ('Column Names and data Type information')
display (df_np_summary_types)
print ()

# format column name and number of empty occurrencies for easier view
df_np_summary_vempty = (
      df_np_summary.isna().sum()
      .reset_index()
      .rename(columns={"index":"Column Name",0:"Empty Values"})
    )

print ('\n Missing Values\n')
display (df_np_summary_vempty);

print ('\n Describe Numeric values\n')
display(df_np_summary.describe())
print ()

Load np_summary data file
Number of Rows: 135
Number of Columns: 10

Sample for sanity checking

,Reg,Type,ParkName,DayVisits,OtherLodging,OtherCamping,TentCampers,RVCampers,BackcountryCampers,Acres
16,IM,NM,Dinosaur National Monument,304312.0,0.0,0.0,17207.0,13604.0,34591.0,210281.92
12,IM,NM,Cedar Breaks National Monument,899676.0,0.0,0.0,2501.0,1776.0,0.0,6154.60
39,IM,NP,Big Bend National Park,388290.0,48280.0,11654.0,64593.0,27385.0,41793.0,801163.21
86,NE,NS,Assateague Island National Seashore,2267821.0,0.0,0.0,40826.0,20735.0,973.0,41346.50
17,IM,NM,El Malpais National Monument,157440.0,0.0,0.0,0.0,0.0,0.0,114347.11

Column Names and data Type information

          Column Name Data Type
0                 Reg    object
1                Type    object
2            ParkName    object
3           DayVisits   float64
4        OtherLodging   float64
5        OtherCamping   float64
6         TentCampers   float64
7           RVCampers   float64
8  BackcountryCampers   float64
9               Acres   float64

 Missing Values

          Column Name  Empty Values
0                 Reg             0
1                Type             0
2            ParkName             0
3           DayVisits             0
4        OtherLodging             0
5        OtherCamping             0
6         TentCampers             0
7           RVCampers             0
8  BackcountryCampers             0
9               Acres             0

 Describe Numeric values

,DayVisits,OtherLodging,OtherCamping,TentCampers,RVCampers,BackcountryCampers,Acres
count,1.350000e+02,135.000000,135.000000,135.000000,135.000000,135.000000,1.350000e+02
mean,9.660225e+05,22238.800000,7977.311111,23870.807407,14761.325926,12306.881481,2.857403e+05
std,1.568838e+06,97536.288961,56375.721363,60590.834702,40977.096735,37946.467226,7.655633e+05
min,1.146000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,3.500000e-01
25%,7.647350e+04,0.000000,0.000000,0.000000,0.000000,0.000000,1.196755e+03
50%,3.882900e+05,0.000000,0.000000,0.000000,0.000000,36.000000,3.397084e+04
75%,1.083526e+06,0.000000,0.000000,12676.000000,11975.500000,4897.000000,2.047386e+05
max,1.131279e+07,743546.000000,583068.000000,490431.000000,376744.000000,330703.000000,6.587071e+06

In [229]:
#2. Create a new column SqMiles by converting Acres to square miles (Acres * 0.0015625).

df_np_summary_new = df_np_summary.copy()

# use number indicated
multiplier =  0.0015625
# create new field in dataframe
df_np_summary_new['SqMiles'] = df_np_summary_new.Acres * multiplier

print ('New Column SqMiles Added \n')
display(df_np_summary_new.sample(5))

New Column SqMiles Added

,Reg,Type,ParkName,DayVisits,OtherLodging,OtherCamping,TentCampers,RVCampers,BackcountryCampers,Acres,SqMiles
129,SE,NS,Canaveral National Seashore,1629944.0,0.0,0.0,0.0,0.0,2636.0,57661.69,90.096391
11,IM,NM,Casa Grande Ruins National Monument,75752.0,0.0,0.0,0.0,0.0,0.0,472.50,0.738281
8,IM,NM,Bandelier National Monument,198478.0,0.0,0.0,5704.0,4164.0,665.0,33676.67,52.619797
104,PW,NP,Lassen Volcanic National Park,536068.0,6182.0,0.0,59742.0,27633.0,9057.0,106589.02,166.545344
1,A,NP,Kenai Fjords National Park,346534.0,0.0,0.0,1514.0,0.0,648.0,669650.05,1046.328203

In [231]:
#3.Create a new column Camping as the sum of OtherCamping, TentCampers, RVCampers, and BackcountryCampers.

#create new column adding values from All Campers
df_np_summary_new['Camping'] = df_np_summary_new.OtherCamping + df_np_summary_new.TentCampers+ df_np_summary_new.RVCampers + df_np_summary_new.BackcountryCampers

#display values
print ('New Column Camping Added \n')
display(df_np_summary_new.sample(5))

New Column Camping Added

,Reg,Type,ParkName,DayVisits,OtherLodging,OtherCamping,TentCampers,RVCampers,BackcountryCampers,Acres,SqMiles,Camping
78,NE,NM,Booker T. Washington National Monument,23440.0,0.0,0.0,0.0,0.0,0.0,239.01,0.373453,0.0
133,SE,NS,Gulf Islands National Seashore,4771309.0,0.0,0.0,37870.0,140712.0,119.0,138305.52,216.102375,178701.0
105,PW,NP,Mount Rainier National Park,1356913.0,42223.0,0.0,64265.0,28981.0,57636.0,236381.64,369.346313,150882.0
42,IM,NP,Canyonlands National Park,776218.0,0.0,0.0,13513.0,8288.0,86227.0,337597.83,527.496609,108028.0
33,IM,NM,Tonto National Monument,38048.0,0.0,0.0,0.0,0.0,0.0,1120.00,1.750000,0.0

In [266]:
#4.Format SqMiles and Camping columns to include commas and zero decimal places.

#creating copies for formatting
df_np_summary_fmt = df_np_summary_new.copy()

#to allow display with comma and decimal places the variables will be converted to character
df_np_summary_fmt["SqMiles"] = df_np_summary_fmt["SqMiles"].map("{:,.2f}".format)
df_np_summary_fmt.Camping = df_np_summary_fmt["Camping"].map("{:,.2f}".format)

print('New variables (SqMiles and Camping) now are formatted including zero and decimal places')
print('Sample is larger as an atempt to find large numbers')
display(df_np_summary_fmt.sample(15))

New variables (SqMiles and Camping) now are formatted including zero and decimal places
Sample is larger as an atempt to find large numbers

,Reg,Type,ParkName,DayVisits,OtherLodging,OtherCamping,TentCampers,RVCampers,BackcountryCampers,Acres,SqMiles,Camping
128,SE,NP,Virgin Islands National Park,411343.0,14214.0,15842.0,0.0,0.0,0.0,14948.46,23.36,"15,842.00"
6,IM,NM,Alibates Flint Quarries National Monument,8153.0,0.0,0.0,0.0,0.0,0.0,1370.97,2.14,0.00
133,SE,NS,Gulf Islands National Seashore,4771309.0,0.0,0.0,37870.0,140712.0,119.0,138305.52,216.10,"178,701.00"
41,IM,NP,Bryce Canyon National Park,2365110.0,56844.0,0.0,38192.0,62768.0,2684.0,35835.08,55.99,"103,644.00"
72,MW,NP,Wind Cave National Park,617377.0,0.0,0.0,4093.0,4401.0,493.0,33970.84,53.08,"8,987.00"
94,PW,NM,Lava Beds National Monument,127699.0,0.0,0.0,8229.0,2128.0,49.0,46692.42,72.96,"10,406.00"
23,IM,NM,Hovenweep National Monument,42862.0,0.0,0.0,1184.0,1211.0,0.0,784.93,1.23,"2,395.00"
35,IM,NM,Walnut Canyon National Monument,152444.0,0.0,0.0,0.0,0.0,0.0,3529.26,5.51,0.00
109,PW,NP,Sequoia National Park,1254688.0,63940.0,0.0,149714.0,69732.0,36247.0,404062.63,631.35,"255,693.00"
79,NE,NM,Castle Clinton National Monument,4812930.0,0.0,0.0,0.0,0.0,0.0,1.00,0.00,0.00
54,IM,NP,Yellowstone National Park,4257177.0,579227.0,583068.0,101639.0,68991.0,44663.0,2219790.71,"3,468.42","798,361.00"
28,IM,NM,Organ Pipe Cactus National Monument,234186.0,0.0,0.0,7188.0,19926.0,64.0,330688.86,516.70,"27,178.00"
77,NE,NM,African Burial Ground National Monument,46526.0,0.0,0.0,0.0,0.0,0.0,0.35,0.00,0.00
122,SE,NP,Congaree National Park,143843.0,0.0,0.0,0.0,0.0,286.0,26275.82,41.06,286.00
103,PW,NP,Kings Canyon National Park,607479.0,50079.0,0.0,110490.0,32686.0,12046.0,461901.20,721.72,"155,222.00"

In [271]:
#5.Save the updated dataset with only the following columns:
#Reg, ParkName, DayVisits, OtherLodging, Acres, SqMiles, Camping. Deliverables: Python script with the processed DataFrame.

df_np_summary_fmt.to_csv("np_summary_updated.csv",
                         columns=['Reg', 'ParkName', 'DayVisits', 'OtherLodging', 'Acres', 'SqMiles', 'Camping'],
                         index=False)